project:
  type: website
    
website:
  site-url: https://armelleblln.github.io/
  repo-url: https://github.com/armelleblln/armelleblln.github.io/
  favicon: favicon.png
  title: "Armelle Ballian"
  reader-mode: true
  back-to-top-navigation: true
  navbar:
    left:
      - text: "About me"
        href: about.qmd  
      - text: "My research"
        href: index.qmd



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
  
