project:
  type: website
    
website:
  site-url: https://armelleblln.github.io/
  repo-url: https://github.com/armelleballian/
  favicon: favicon.png
  title: "Dr. Armelle Ballian"
  reader-mode: true
  back-to-top-navigation: true
  body-footer: _footer.qmd
  navbar:
    left:
      - text: "About me"
        href: about.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Teaching and Student Supervision"
        href: teaching.qmd
      - text: "Honors and Awards"
        href: awards.qmd
      - text: "Service"
        href: service.qmd
      - text: "Public outreach"
        href: outreach.qmd
      - text: "CV"
        href: cv.qmd
        


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
