project:
  type: website
    
website:
  site-url: https://armelleblln.github.io/
  repo-url: https://github.com/armelleblln/armelleblln.github.io/
  favicon: favicon.png
  title: "Armelle Ballian"
  reader-mode: true
  back-to-top-navigation: true
  body-footer: _footer.qmd
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About me"
        href: about.qmd  
      - text: "Publications"
        href: publi.qmd
      - text: "Curriculum Vitae"
        href: cv.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
  
