---
pagetitle: "Armelle Ballian - Publications"
---
:::{#template-area}
## Publications 
<u>Ballian, A.</u>, Meijers, M. J. M., Cojan, I., Huyghe, D., Bernecker, M., Methner, K., Tagliavento, M., Fiebig, J., and Mulch, A. (2025).
Middle Miocene climate evolution in the Northern Mediterranean region (Digne-Valensole basin, SE France), Clim. Past, 21, 841–856 [🔍](https://doi.org/10.5194/cp-21-841-2025){target="_blank"}  

Boateng, D., Mutz, S., Methner, K., <u>Ballian, A.</u>, Meijers, M. J. M., Mulch, A., Ehlers, T. A. (2025). Refining paleoelevation estimates of the European Alps by simulating Middle Miocene climate and δ18O responses to diachronous surface uplift scenarios, Global and Planetary Change, 251, 104808, ISSN 0921-8181, [🔍](https://doi.org/10.1016/j.gloplacha.2025.104808){target="_blank"} 

<u>Ballian, A.</u>, Chawchai, S., Miocic, J. M., Charoenchatree, W., Bissen, R., and Preusser, F. (2024).  
Late Holocene coastal dynamics south of the Chanthaburi estuary, eastern Gulf of Thailand.  Quaternary Research. 117:19-29 [🔍](https://www.cambridge.org/core/journals/quaternary-research/article/abs/late-holocene-coastal-dynamics-south-of-the-chanthaburi-estuary-eastern-gulf-of-thailand/CA506FAE3DF018CE3D7D2AEA52C6F4C9){target="_blank"} 

Bernecker, M., Hofmann, S., Staudigel, P. T., Davies, A. J., Tagliavento, M., Meijer, N., <u>Ballian, A.</u>, and Fiebig, J. (2023). A robust methodology for triple (∆ 47,∆ 48,∆ 49) clumped isotope analysis of carbonates. Chemical Geology, 642, 121803 [🔍](https://www.sciencedirect.com/science/article/pii/S0009254123005041){target="_blank"} 

Boateng, D., Mutz, S. G., <u>Ballian, A.</u>, Meijers, M. J. M. , Methner, K., Botsyun, S., Mulch, A., and Ehlers, T. A. (2023).  
The effects of diachronous surface uplift of the European Alps on regional climate and the oxygen isotopic composition of precipitation. Earth System Dynamics Discussions, 1-45 [🔍](https://esd.copernicus.org/articles/14/1183/2023/esd-14-1183-2023.pdf){target="_blank"} 
:::
## Conference abstracts  
Ballian, A., Meijers, M. J. M., Methner, K., Cojan, I., Huyghe, D., Fiebig, J., & Mulch, A. (2023). Miocene (23-13 Ma) continental paleotemperature record from the northern Mediterranean region (Digne-Valensole basin, SE France) within a global climatic framework. Annual 4D-MB Scientific Meeting. [🔍](http://dx.doi.org/10.17169/refubium-40985){target="_blank"} 

Ballian, A., Boateng, D., Mutz, S. G., Meijers, M. J. M., Methner, K., Ehlers, T., & Mulch, A. (2023). The Alps Paleoelevation and Paleoclimate Experiment : Reconstructing Eastward Propagation of Surface Uplift in the ALPS (REAL). Annual 4D-MB Scientific Meeting. [🔍](http://dx.doi.org/10.17169/refubium-40986){target="_blank"} 

Ballian, A., Meijers, M. J. M., Cojan, I., Huyghe, D., Fiebig, J., & Mulch, A. (2022). Early-Miocene stable isotope paleoaltimetry estimates for the Central Alps. EGU23 [🔍](https://scholar.google.com/citations?view_op=view_citation&hl=fr&user=aId4LewAAAAJ&citation_for_view=aId4LewAAAAJ:u5HHmVD_uO8C){target="_blank"}  

Ballian, A., Meijers, M. J. M., Methner, K., Cojan, I., Huyghe, D., Fiebig, J., & Mulch, A. (2022). A Miocene (23–12.5 Ma) continental paleotemperature record from the northern Mediterranean region (Digne-Valensole Basin, SE France). EGU23 [🔍](https://meetingorganizer.copernicus.org/EGU23/EGU23-14517.html){target="_blank"}  


---







