---
pagetitle: "Armelle Ballian - Publications"
---
:::{#template-area}
## Publications 
<u>Ballian, A.</u>, Meijers, M. J. M., Boateng, D., Cojan, I., Mutz, S. G., Ehlers, T. A., and Mulch, A. (under review).
Oxygen isotopic composition of Miocene meteoric water (d18Ow) in Alpine foreland basins. Geochemistry, Geophysics, Geosystems.

Liu, X., Liu, Y. <u>Ballian, A.</u>, Bernecker, M., Fiebig, J., Rao, Y., Ding, L., and Mulch, A. (2026).
Low Elevation and Humid Climate in the Eocene Gerze Basin, Central Tibet: Insights from Multi-Proxy Isotopic Analyses. Global and Planetary Change, 105547, ISSN 0921-8181.[🔍](https://doi.org/10.1016/j.gloplacha.2026.105547){target="_blank"}  

<u>Ballian, A.</u>, Meijers, M. J. M., Cojan, I., Huyghe, D., Bernecker, M., Methner, K., Tagliavento, M., Fiebig, J., and Mulch, A. (2025).
Middle Miocene climate evolution in the Northern Mediterranean region (Digne-Valensole basin, SE France), Clim. Past, 21, 841–856 [🔍](https://doi.org/10.5194/cp-21-841-2025){target="_blank"}  

Boateng, D., Mutz, S., Methner, K., <u>Ballian, A.</u>, Meijers, M. J. M., Mulch, A., Ehlers, T. A. (2025). Refining paleoelevation estimates of the European Alps by simulating Middle Miocene climate and δ18O responses to diachronous surface uplift scenarios, Global and Planetary Change, 251, 104808, ISSN 0921-8181, [🔍](https://doi.org/10.1016/j.gloplacha.2025.104808){target="_blank"} 

<u>Ballian, A.</u>, Chawchai, S., Miocic, J. M., Charoenchatree, W., Bissen, R., and Preusser, F. (2024).  
Late Holocene coastal dynamics south of the Chanthaburi estuary, eastern Gulf of Thailand.  Quaternary Research. 117:19-29 [🔍](https://www.cambridge.org/core/journals/quaternary-research/article/abs/late-holocene-coastal-dynamics-south-of-the-chanthaburi-estuary-eastern-gulf-of-thailand/CA506FAE3DF018CE3D7D2AEA52C6F4C9){target="_blank"} 

Bernecker, M., Hofmann, S., Staudigel, P. T., Davies, A. J., Tagliavento, M., Meijer, N., <u>Ballian, A.</u>, and Fiebig, J. (2023). A robust methodology for triple (∆ 47,∆ 48,∆ 49) clumped isotope analysis of carbonates. Chemical Geology, 642, 121803 [🔍](https://www.sciencedirect.com/science/article/pii/S0009254123005041){target="_blank"} 

Boateng, D., Mutz, S. G., <u>Ballian, A.</u>, Meijers, M. J. M. , Methner, K., Botsyun, S., Mulch, A., and Ehlers, T. A. (2023).  
The effects of diachronous surface uplift of the European Alps on regional climate and the oxygen isotopic composition of precipitation. Earth System Dynamics Discussions, 1-45 [🔍](https://esd.copernicus.org/articles/14/1183/2023/esd-14-1183-2023.pdf){target="_blank"} 
:::

## Conference abstracts  

Ballian, A., Meijers, M. M. J., Cojan, I., Huygue, D., Methner, K., Boateng, D., Mutz, S. G., Kurz, W., Krsnik, E., Zwingmann, H., Rolland, Y., Ehlers, T., Fiebig, J., and Mulch, A.: Early to Middle Miocene paleoaltimetry results from the European Alps. GeoSaxonia, 2024, 10.48380/5958-bd76. [🔍](https://www.dggv.de/e-publikationen/early-to-middle-miocene-paleoaltimetry-results-from-the-european-alps/){target="_blank"}

Ballian, A., Meijers, M. M. J., Cojan, I., Huygue, D., Bernecker, M., Methner, K., Tagliavento, T., Fiebig, J., and Mulch, A.: Miocene (23-13 Ma) Continental Paleotemperatures in the Northern Mediterranean Region within a Global Climate Framework (Digne-Valensole
Basin, SE France), poster, 9th International Clumped Isotope Workshop, Stony Brook University, Stony Brook, USA, 25–28 Aug 2024, 2024.

Ballian, A., Meijers, M. M. J., Cojan, I., Huygue, D., Methner, K., Boateng, D., Mutz, S. G., Kurz, W., Krsnik, E., Zwingmann, H., Rolland, Y., Ehlers, T., Fiebig, J., and Mulch, A.: Stable isotope paleoaltimetry reveals Early to Middle Miocene along-strike elevation
differences of the European Alps, EGU General Assembly 2024, oral presentation, Vienna, Austria, 14–19 Apr 2024, EGU24-18901, 2024. [🔍](https://doi.org/10.5194/egusphere-egu24-18901){target="_blank"}

Ballian, A., Meijers, M. M. J., Methner, K., Cojan, I., Huygue, D., Fiebig, J., and Mulch, A.: Miocene (23-13 Ma) Northern Mediterranean continental paleotemperatures within a global climate framework (Digne-Valensole Basin, SE France), oral presentation, AGU Fall
Meeting 2023 held in San Francisco, USA, 11–15 Dec 2023, Session: Paleoceanography and Paleoclimatology / Advances in the Miocene Climate Dynamics II Oral, id. PP54A-04., 2023. [🔍](https://ui.adsabs.harvard.edu/abs/2023AGUFMPP54A..04B/abstract){target="_blank"}

Ballian, A., Meijers, M. M. J., Cojan, I., Huygue, D., Methner, K., Boateng, D., Mutz, S. G., Walter, K., Krsnik, E., Zwingmann, H., Rolland, Y., Ehlers, T., Fiebig, J., and Mulch, A.: Early to Middle Miocene paleoaltimetry results from the Central and Eastern
European Alps, poster, AGU Fall Meeting 2023 held in San Francisco, USA, 11–15 Dec 2023, id. PP54A-04., 2023. [🔍](https://ui.adsabs.harvard.edu/abs/2023AGUFM.T51E0159B/abstract){target="_blank"}

Ballian, A., Meijers, M. J. M., Methner, K., Cojan, I., Huyghe, D., Fiebig, J., & Mulch, A. (2023). Miocene (23-13 Ma) continental paleotemperature record from the northern Mediterranean region (Digne-Valensole basin, SE France) within a global climatic framework. Annual 4D-MB Scientific Meeting. [🔍](http://dx.doi.org/10.17169/refubium-40985){target="_blank"} 

Ballian, A., Boateng, D., Mutz, S. G., Meijers, M. J. M., Methner, K., Ehlers, T., & Mulch, A. (2023). The Alps Paleoelevation and Paleoclimate Experiment : Reconstructing Eastward Propagation of Surface Uplift in the ALPS (REAL). Annual 4D-MB Scientific Meeting. [🔍](http://dx.doi.org/10.17169/refubium-40986){target="_blank"} 

Ballian, A., Meijers, M. J. M., Methner, K., Cojan, I., Huyghe, D., Fiebig, J., & Mulch, A. (2023). A Miocene (23–12.5 Ma) continental paleotemperature record from the northern Mediterranean region (Digne-Valensole Basin, SE France). EGU23 [🔍](https://meetingorganizer.copernicus.org/EGU23/EGU23-14517.html){target="_blank"}  

Ballian, A., Meijers, M. J. M., Cojan, I., Huyghe, D., Fiebig, J., & Mulch, A. (2022). Early-Miocene stable isotope paleoaltimetry estimates for the Central Alps. EGU22 [🔍](https://meetingorganizer.copernicus.org/EGU22/EGU22-2346.html){target="_blank"}  

:::

---







