---
pagetitle: "Teaching Experience and Student Supervision"
---
:::{#template-area}
## Teaching Experience 
| | |
|---|---|
| **Summer Semester 2026** | **Lecturer and co-coordinator** |
|  | Environmental Isotope Chemistry (M208), University of Tübingen|
|  | Climate Dynamics and Climate Modeling (M322), University of Tübingen|
|  | **Lab practicals** |
|  | Environmental Isotope Chemistry (M208), University of Tübingen|
|  | **One-day excursions** |
|  | Excursion to the Swabian Alb - Karst Processes Below the Surface|
| **Winter Semester 2025-2026** | **Lecturer and co-coordinator** |
|  | Global Change (M229), University of Tübingen |
| **Summer Semester 2025** | **Guest lecture and lab practicals** |
|  | Environmental Isotope Chemistry (M208), University of Tübingen|
|  | **One-day excursion** |
|  | Excursion to the Swabian Alb - Karst Processes at the Surface|
:::
## Student Supervision 
| **Bachelor thesis** | |
| **Summer Semester 2026** | J. Christmann (Water isotopes, trace elements and PFAS in the Swabian Alb karst system)|
| **Summer Semester 2025** | J. Baum (Stable isotope compositions in precipitation on the Swabian Alb)|

| **Master thesis** | |
| **Summer Semester 2026** | D. Lo Triglia (Tracing isotopes from rain to calcite)|

---







